import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import '../models/report.dart';
import '../services/location_service.dart';
import '../services/report_service.dart';
import '../utils/validators.dart';
import '../widgets/status_badge.dart';
class ReportScreen extends StatefulWidget { const ReportScreen({required this.incidentType,this.isEmergency=false,super.key}); final String incidentType; final bool isEmergency; @override State<ReportScreen> createState()=>_ReportScreenState(); }
class _ReportScreenState extends State<ReportScreen>{final form=GlobalKey<FormState>(),description=TextEditingController(); Position? position; XFile? photo; bool locating=false, submitting=false;
  @override void initState(){super.initState();getLocation();}
  Future<void> getLocation()async{setState(()=>locating=true);try{position=await LocationService().currentPosition();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('LocationException: ',''))));}finally{if(mounted)setState(()=>locating=false);}}
  Future<void> submit()async{if(!form.currentState!.validate())return;if(position==null){await getLocation();if(position==null)return;}if(widget.isEmergency){final yes=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Submit emergency report?'),content:const Text('This will send your current location and report to the configured iBantay responder system.'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Submit'))]));if(yes!=true)return;}setState(()=>submitting=true);try{final report=await ReportService().submit(incidentType:widget.incidentType,description:description.text,latitude:position!.latitude,longitude:position!.longitude,accuracy:position!.accuracy,image:photo);if(mounted)showSuccess(report);}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Report submission failed. Check your internet connection and try again.')));}finally{if(mounted)setState(()=>submitting=false);}}
  void showSuccess(IncidentReport report)=>showDialog(context:context,barrierDismissible:false,builder:(c)=>AlertDialog(icon:const Icon(Icons.check_circle,color:Colors.green,size:48),title:const Text('Emergency report submitted successfully.'),content:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Report ID: ${report.reportId}'),const SizedBox(height:8),Row(children:[const Text('Status: '),StatusBadge(report.status)])]),actions:[FilledButton(onPressed:()=>Navigator.of(c).popUntil((r)=>r.isFirst),child:const Text('Done'))]));
  @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text('${widget.incidentType} report')),body:SafeArea(child:SingleChildScrollView(child:Padding(padding:const EdgeInsets.all(20),child:Form(key:form,child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(widget.incidentType,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),const SizedBox(height:16),TextFormField(controller:description,validator:(v)=>requiredText(v,field:'Description'),maxLines:4,decoration:const InputDecoration(labelText:'Description',hintText:'Describe what is happening and any safety details.',border:OutlineInputBorder())),const SizedBox(height:16),Card(child:Padding(padding:const EdgeInsets.all(16),child:locating?const Row(children:[CircularProgressIndicator(),SizedBox(width:12),Text('Obtaining current GPS location…')]):position==null?Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Location unavailable'),TextButton(onPressed:getLocation,child:const Text('TRY LOCATION AGAIN'))]):Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Current GPS location',style:TextStyle(fontWeight:FontWeight.bold)),Text('Latitude: ${position!.latitude.toStringAsFixed(6)}'),Text('Longitude: ${position!.longitude.toStringAsFixed(6)}'),Text('Accuracy: ±${position!.accuracy.toStringAsFixed(1)} m'),TextButton(onPressed:getLocation,child:const Text('REFRESH LOCATION'))]))),const SizedBox(height:8),OutlinedButton.icon(onPressed:()async{photo=await ImagePicker().pickImage(source:ImageSource.camera,imageQuality:80);setState((){});},icon:const Icon(Icons.camera_alt_outlined),label:Text(photo==null?'Add optional photo':'Photo attached: ${photo!.name}')),const SizedBox(height:20),FilledButton.icon(style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(54),backgroundColor:widget.isEmergency?Colors.red:null),onPressed:submitting?null:submit,icon:const Icon(Icons.send),label:Text(submitting?'SENDING REPORT…':'${widget.isEmergency?'CONFIRM EMERGENCY':'SUBMIT'} REPORT'))])))));
}
